IMAGE        ?= bbb-builder
HOST         ?= 192.168.7.2
TFTP_DIR     ?= /srv/tftp
DEV          ?= /dev/sda
STORAGE_BASE ?=

DRIVER     ?=
BB         ?= core-image-minimal
BSP_ROOT   := $(CURDIR)
POKY_DIR   ?= $(abspath $(BSP_ROOT)/poky)
EFFECTIVE_STORAGE_BASE := $(strip $(STORAGE_BASE))

ifneq ($(strip $(EFFECTIVE_STORAGE_BASE)),)
ifeq ($(filter /%,$(EFFECTIVE_STORAGE_BASE)),)
$(error STORAGE_BASE must be an absolute path)
endif
endif

BUILD_DIR_HOST       ?= $(if $(EFFECTIVE_STORAGE_BASE),$(EFFECTIVE_STORAGE_BASE)/build,$(BSP_ROOT)/build)
YOCTO_STORAGE_ROOT   ?= $(if $(EFFECTIVE_STORAGE_BASE),$(EFFECTIVE_STORAGE_BASE)/yocto,$(BSP_ROOT)/build)

BUILD_DIR            ?= $(if $(EFFECTIVE_STORAGE_BASE),$(EFFECTIVE_STORAGE_BASE)/build,/workspace/build)
YOCTO_BUILD_DIR      ?= /workspace/build
YOCTO_BUILD_DIR_HOST ?= $(if $(filter /workspace/%,$(YOCTO_BUILD_DIR)),\
                             $(BSP_ROOT)/$(patsubst /workspace/%,%,$(YOCTO_BUILD_DIR)),\
                             $(YOCTO_BUILD_DIR))

YOCTO_TMPDIR         ?= $(if $(EFFECTIVE_STORAGE_BASE),$(YOCTO_STORAGE_ROOT)/tmp,$(YOCTO_BUILD_DIR)/tmp)
YOCTO_TMPDIR_HOST    ?= $(if $(EFFECTIVE_STORAGE_BASE),$(YOCTO_STORAGE_ROOT)/tmp,build/tmp)

YOCTO_DL_DIR         ?= $(if $(EFFECTIVE_STORAGE_BASE),$(YOCTO_STORAGE_ROOT)/downloads,$(YOCTO_BUILD_DIR)/downloads)
YOCTO_DL_DIR_HOST    ?= $(if $(EFFECTIVE_STORAGE_BASE),$(YOCTO_STORAGE_ROOT)/downloads,build/downloads)

YOCTO_SSTATE_DIR      ?= $(if $(EFFECTIVE_STORAGE_BASE),$(YOCTO_STORAGE_ROOT)/sstate-cache,$(YOCTO_BUILD_DIR)/sstate-cache)
YOCTO_SSTATE_DIR_HOST ?= $(if $(EFFECTIVE_STORAGE_BASE),$(YOCTO_STORAGE_ROOT)/sstate-cache,build/sstate-cache)

YOCTO_AUTO_CONF      ?= $(YOCTO_BUILD_DIR)/conf/auto.conf
YOCTO_AUTO_CONF_HOST ?= $(YOCTO_BUILD_DIR_HOST)/conf/auto.conf
YOCTO_DEPLOY_DIR     ?= $(YOCTO_TMPDIR_HOST)/deploy/images/beaglebone-custom
YOCTO_WIC            ?= $(YOCTO_DEPLOY_DIR)/bbb-image-beaglebone-custom.wic

ARCH                 ?= arm
CROSS_COMPILE        ?= arm-linux-gnueabihf-
KERNEL_BUILD_MODE    ?= dev
KERNEL_DEV_DEBUG     ?= 1
KERNEL_RECONFIGURE   ?= 0
KERNEL_JOBS          ?= $(shell nproc)
REPRODUCIBLE_BUILD   ?= 0

BUILD_SCRIPT := scripts/build.sh
VERIFY_SCRIPT := scripts/kernel_verify.sh

DOCKER_KERNEL_ENV = \
  -e ARCH=$(ARCH) \
  -e BUILD_DIR=$(BUILD_DIR) \
  -e CROSS_COMPILE=$(CROSS_COMPILE) \
  -e KERNEL_BUILD_MODE=$(KERNEL_BUILD_MODE) \
  -e KERNEL_DEV_DEBUG=$(KERNEL_DEV_DEBUG) \
  -e KERNEL_JOBS=$(KERNEL_JOBS) \
  -e KERNEL_RECONFIGURE=$(KERNEL_RECONFIGURE) \
  -e REPRODUCIBLE_BUILD=$(REPRODUCIBLE_BUILD)

DOCKER_WORKSPACE = \
  -v "$(BSP_ROOT):/workspace"

STORAGE_BASE_MOUNT = $(if $(EFFECTIVE_STORAGE_BASE),-v "$(EFFECTIVE_STORAGE_BASE):$(EFFECTIVE_STORAGE_BASE)",)

DOCKER_RUN = docker run --rm \
  $(DOCKER_KERNEL_ENV) \
  $(DOCKER_WORKSPACE) \
  $(STORAGE_BASE_MOUNT) \
  $(IMAGE)

DOCKER_IT = docker run --rm -it \
  $(DOCKER_KERNEL_ENV) \
  $(DOCKER_WORKSPACE) \
  $(STORAGE_BASE_MOUNT) \
  $(IMAGE)

DOCKER_YOCTO_IT = docker run --rm -it \
  -e ARCH=$(ARCH) \
  -e CROSS_COMPILE=$(CROSS_COMPILE) \
  $(DOCKER_WORKSPACE) \
  $(STORAGE_BASE_MOUNT) \
  -v "$(POKY_DIR):/home/builder/poky" \
  $(IMAGE)

define run-kernel-make
	$(DOCKER_RUN) bash -c "cd linux && make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) $(1)"
endef

define run-yocto-command
	$(DOCKER_YOCTO_IT) bash -c "\
		cd /home/builder/poky && \
		source oe-init-build-env $(YOCTO_BUILD_DIR) && \
		mkdir -p "$(dir $(YOCTO_AUTO_CONF))" && \
		: > "$(YOCTO_AUTO_CONF)" && \
		printf '%s\n' '# Auto-generated by Makefile. Do not edit.' >> "$(YOCTO_AUTO_CONF)"\
		$(if $(EFFECTIVE_STORAGE_BASE), && printf '%s\n' 'TMPDIR = \"$(YOCTO_TMPDIR)\"' 'DL_DIR = \"$(YOCTO_DL_DIR)\"' 'SSTATE_DIR = \"$(YOCTO_SSTATE_DIR)\"' >> "$(YOCTO_AUTO_CONF)",) && \
		$(1)"
endef

define yocto-stage-step
	$(call run-yocto-command,bitbake $(1))
endef

define yocto-clean-tmp
	rm -rf "$(YOCTO_TMPDIR_HOST)"
endef

define yocto-clean-state
	$(call yocto-clean-tmp)
	rm -f "$(YOCTO_AUTO_CONF_HOST)"
endef

define yocto-clean-caches
	rm -rf "$(YOCTO_DL_DIR_HOST)" "$(YOCTO_SSTATE_DIR_HOST)"
endef

define require-driver
	@test -n "$(DRIVER)" || \
		(echo "Error: specify DRIVER=<name>  e.g. make driver DRIVER=led-gpio" && exit 1)
endef

# Build targets
.PHONY: all kernel kernel-dev kernel-reproducible kernel-verify uboot driver

# Container / Yocto
.PHONY: docker shell yocto-shell bitbake \
	yocto-stage yocto-stage-cleanstep \
	yocto-stage-uboot yocto-stage-kernel yocto-stage-drivers \
	yocto-stage-apps yocto-stage-gst yocto-stage-image yocto-deploy yocto-flash \
	yocto-clean-tmp yocto-clean yocto-clean-all docker-clean docker-clean-keep-image

# Board operations
.PHONY: deploy flash sd-rootfs-check

# Cleanup
.PHONY: clean kernel-clean uboot-clean drivers-clean

# Quality / misc
.PHONY: check dtbs-check help

help:
	@printf '%s\n' \
		'BeagleBone Black BSP' \
		'' \
		'Build (runs inside Docker):' \
		'  make kernel               Build kernel using KERNEL_BUILD_MODE=$(KERNEL_BUILD_MODE)' \
		'  make kernel-dev           Build kernel for fast development' \
		'  make kernel-reproducible  Build kernel with reproducible settings' \
		'  make kernel-verify        Run host-side Phase 3 kernel/DTS gates' \
		'  make uboot                Build MLO + u-boot.img' \
		'  make driver DRIVER=<name> Build out-of-tree driver' \
		'  make all                  Build kernel + uboot + all drivers' \
		'' \
		'Kernel knobs:' \
		'  KERNEL_BUILD_MODE=dev|reproducible' \
		'  KERNEL_JOBS=<n> KERNEL_RECONFIGURE=1 KERNEL_DEV_DEBUG=0' \
		'' \
		'Yocto:' \
		'  make yocto-shell          Interactive shell with Yocto env loaded' \
		'  make bitbake BB=<target>  Run bitbake (default: core-image-minimal)' \
		'  make yocto-stage          Build low-disk base Yocto stages (no full image)' \
		'  make yocto-stage-cleanstep' \
		'                            Build base stages and remove build/tmp after each stage' \
		'  make yocto-stage-gst      Build optional heavy gstreamer-demo app stage' \
		'  make yocto-stage-image    Build optional full bbb-image stage' \
		'  make yocto-deploy         Copy Yocto zImage + DTB to TFTP dir' \
		'  make yocto-flash DEV=/dev/sdX' \
		'                            Flash Yocto .wic image to SD card' \
		'  make yocto-clean-tmp      Remove Yocto tmp dir only' \
		'  make yocto-clean          Remove Yocto tmp + generated auto.conf override' \
		'  make yocto-clean-all      Remove Yocto tmp + auto.conf + downloads + sstate-cache' \
		'  YOCTO_DEPLOY_DIR=<path>   Yocto deploy images dir for yocto-deploy' \
		'  YOCTO_WIC=<path>          Yocto .wic image for yocto-flash' \
		'  POKY_DIR=<path>           Yocto poky checkout (default: ./poky)' \
		'  YOCTO_BUILD_DIR=<path>    Build dir passed to oe-init-build-env (default: /workspace/build)' \
		'  STORAGE_BASE=<path>       Optional absolute host path for all build outputs' \
		'' \
		'Common workflows:' \
		'  Manual dev boot:          make kernel && make deploy' \
		'                            U-Boot loads build/kernel artifacts by TFTP' \
		'  Manual SD flash:          make uboot && make kernel && make flash DEV=/dev/sdX' \
		'                            Legacy partition/copy flow, not Yocto .wic' \
		'  Yocto TFTP dev boot:      make yocto-stage-image && make yocto-deploy' \
		'                            U-Boot loads Yocto kernel/DTB by TFTP' \
		'  Yocto SD image flash:     make yocto-stage-image && make yocto-flash DEV=/dev/sdX' \
		'                            Writes the full Yocto .wic image to SD' \
		'  External storage override make yocto-stage-image STORAGE_BASE=/mnt/data/yocto-bbb' \
		'                            Stores manual build outputs in .../build and Yocto state in .../yocto' \
		'' \
		'Docker:' \
		'  make docker               Build Docker image ($(IMAGE))' \
		'  make shell                Interactive shell in Docker container' \
		'  make docker-clean         Remove Docker objects and image $(IMAGE)' \
		'  make docker-clean-keep-image' \
		'                            Remove Docker cache/objects but keep image $(IMAGE)' \
		'' \
		'Board:' \
		'  make deploy TFTP_DIR=<path>' \
		'                            Copy manual build/kernel artifacts to TFTP dir' \
		'  make yocto-deploy TFTP_DIR=<path>' \
		'                            Copy Yocto deploy zImage + DTB to TFTP dir' \
		'  make flash  DEV=<dev>     Flash SD card (default: $(DEV)) — requires root' \
		'  make yocto-flash DEV=/dev/sdX' \
		'                            Flash Yocto .wic image to SD card' \
		'  make sd-rootfs-check DEV=/dev/sdX' \
		'                            Read-only check BBB rootfs files on SD partition 2' \
		'' \
		'Clean:' \
		'  make clean                Remove build/ directory' \
		'  make kernel-clean         Clean kernel build artifacts' \
		'  make uboot-clean          Clean U-Boot build artifacts' \
		'' \
		'Quality:' \
		'  make check                Run shellcheck + checkpatch on scripts and drivers' \
		'  make dtbs-check           Run dtbs_check on custom DTS (requires dtschema in Docker)'

.check-docker:
	@docker image inspect $(IMAGE) >/dev/null 2>&1 || \
		(echo "Error: Docker image '$(IMAGE)' not found. Run 'make docker' first." && exit 1)

.check-poky:
	@test -d "$(POKY_DIR)" || \
		(echo "Error: POKY_DIR '$(POKY_DIR)' not found. Set POKY_DIR=/path/to/poky." && exit 1)
	@test -f "$(POKY_DIR)/oe-init-build-env" || \
		(echo "Error: POKY_DIR '$(POKY_DIR)' is not a Poky checkout." && exit 1)

docker:
	docker build -f docker/Dockerfile -t $(IMAGE) .

docker-clean:
	docker system prune -a --volumes -f
	docker builder prune -a -f

docker-clean-keep-image: .check-docker
	docker builder prune -a -f
	docker container prune -f
	docker volume prune -f
	docker image prune -f

kernel: .check-docker
	$(DOCKER_RUN) bash $(BUILD_SCRIPT) kernel $(KERNEL_BUILD_MODE)

kernel-dev: KERNEL_BUILD_MODE = dev
kernel-dev: .check-docker
	$(DOCKER_RUN) bash $(BUILD_SCRIPT) kernel dev

kernel-reproducible: KERNEL_BUILD_MODE = reproducible
kernel-reproducible: .check-docker
	$(DOCKER_RUN) bash $(BUILD_SCRIPT) kernel reproducible

kernel-verify: .check-docker
	$(DOCKER_RUN) bash $(VERIFY_SCRIPT)

uboot: .check-docker
	$(DOCKER_RUN) bash $(BUILD_SCRIPT) uboot

driver: .check-docker
	$(require-driver)
	$(DOCKER_RUN) bash $(BUILD_SCRIPT) driver $(DRIVER)

all: .check-docker
	$(DOCKER_RUN) bash $(BUILD_SCRIPT) all

shell: .check-docker
	$(DOCKER_IT) bash

yocto-shell: .check-docker .check-poky
	$(call run-yocto-command,exec bash)

bitbake: .check-docker .check-poky
	$(call run-yocto-command,bitbake $(BB))

yocto-stage-uboot: .check-docker .check-poky
	$(call yocto-stage-step,u-boot-bbb)

yocto-stage-kernel: .check-docker .check-poky
	$(call yocto-stage-step,virtual/kernel)

yocto-stage-drivers: .check-docker .check-poky
	$(call yocto-stage-step,led-gpio sht3x pwm-led)

yocto-stage-apps: .check-docker .check-poky
	$(call yocto-stage-step,sensor-monitor)

yocto-stage-gst: .check-docker .check-poky
	$(call yocto-stage-step,gstreamer-demo)

yocto-stage-image: .check-docker .check-poky
	$(call yocto-stage-step,bbb-image)

yocto-flash:
	sudo bash scripts/flash_yocto_wic.sh "$(DEV)" "$(YOCTO_WIC)"

yocto-deploy:
	YOCTO_DEPLOY_DIR="$(YOCTO_DEPLOY_DIR)" TFTP_DIR="$(TFTP_DIR)" bash scripts/deploy_yocto.sh

yocto-stage: yocto-stage-uboot yocto-stage-kernel yocto-stage-drivers yocto-stage-apps

yocto-clean-tmp:
	$(call yocto-clean-tmp)

yocto-clean:
	$(call yocto-clean-state)

yocto-clean-all: yocto-clean
	$(call yocto-clean-caches)

yocto-stage-cleanstep: .check-docker .check-poky
	$(call yocto-stage-step,u-boot-bbb)
	$(call yocto-clean-tmp)
	$(call yocto-stage-step,virtual/kernel)
	$(call yocto-clean-tmp)
	$(call yocto-stage-step,led-gpio sht3x pwm-led)
	$(call yocto-clean-tmp)
	$(call yocto-stage-step,sensor-monitor)

deploy:
	BUILD_DIR="$(BUILD_DIR_HOST)" TFTP_DIR=$(TFTP_DIR) bash scripts/deploy.sh

flash:
	sudo BUILD_DIR="$(BUILD_DIR_HOST)" bash scripts/flash_sd.sh $(DEV)

sd-rootfs-check:
	sudo bash scripts/check_sd_rootfs.sh "$(DEV)"

clean: kernel-clean uboot-clean drivers-clean
	$(call yocto-clean-state)

drivers-clean:
	rm -rf "$(BUILD_DIR_HOST)/drivers"

kernel-clean: .check-docker
	$(call run-kernel-make,mrproper)
	rm -rf "$(BUILD_DIR_HOST)/linux" "$(BUILD_DIR_HOST)/kernel"

uboot-clean: .check-docker
	$(DOCKER_RUN) bash -c "cd u-boot && make CROSS_COMPILE=$(CROSS_COMPILE) clean"
	rm -rf "$(BUILD_DIR_HOST)/uboot"

check: .check-docker
	$(DOCKER_RUN) shellcheck scripts/*.sh
	$(DOCKER_RUN) bash -c "if [ -d drivers ]; \
	then for d in drivers/*/; do [ -f \$$d/*.c ] && linux/scripts/checkpatch.pl --strict -f \$$d/*.c || true; done; fi"

dtbs-check: .check-docker
	$(call run-kernel-make,dtbs_check DT_SCHEMA_FILES=Documentation/devicetree/bindings/ 2>&1 | \
		grep -E 'am335x-boneblack-custom.*(error|warning)' || echo 'No errors/warnings for custom DTS')
